<a href="https://colab.research.google.com/github/salmaali81/IEEE_DS_Tasks/blob/master/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [ ]:
# One-Dimensional array
import numpy as np
array_1D = np.array([1, 2, 3])
print(array_1D.dtype)
print(array_1D.ndim)



int64
1


In [ ]:
# Two-Dimensional array
array_2D = np.array([[1, 2, 3], [1.2, 2.5, 8.5]])
print(array_2D.dtype)
print(array_2D.ndim)




float64
2


In [ ]:
# Three-Dimensional array
array_3D = np.array([[[1, 2, 3], [1.2, 2.5, 8.5]], [['a', 's', 'm'], ['salma', 'sayed', 'ali']]])
print(array_3D.dtype)
print(array_3D.ndim)







<U32
3


### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [ ]:
# Method one
a = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(a[::-1,::-1,::-1])





[[[10  9  8  7]
  [ 7  6  5  4]
  [ 4  3  2  1]]]


In [ ]:
# Method two
#>**hint**: use flipud function

a = np.fliplr(a)
print(a)





[[[ 7  8  9 10]
  [ 4  5  6  7]
  [ 1  2  3  4]]]


## 6-Make this array as an array one dimensional

In [ ]:
a = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
a=a.flatten()
print(a)

[ 1  2  3  4  4  5  6  7  7  8  9 10]


## 7- Create a 3X2 integer array and Prints its attributes
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [ ]:
r = np.array([[1, 55], [100, 25],[32, 150]])
r = r.astype(np.int16)
print(r)
print(r.dtype)
print(r.shape)
print(r.ndim)
print(r.itemsize)

[[  1  55]
 [100  25]
 [ 32 150]]
int16
(3, 2)
2
2


### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

In [ ]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
for i in range(len(sampleArray)):
  sampleArray[i] = sorted(sampleArray[i])
print(sampleArray)
a=[]
for i in range(len(sampleArray)):
  s=[]
  for j in range(len(sampleArray[i])):
    if(((i+1)%2!=0) and ((j+1)%2==0)):
      s.append(sampleArray[i,j])
  if(len(s)!=0):
    a.append(s)
a = np.array(a)
print(a)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


## 9-How is np.mean() different from np.average() in NumPy?

The main difference between np.mean() and np.average() in NumPy is that np.mean() always calculates the arithmetic mean, while np.average() can calculate a weighted mean if the weights parameter is specified.

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [ ]:
n =int(input())
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
f = np.bincount(arr)
print(f[n])

1
2


## 11-Show how is arr[:,0] different from arr[:,[0]]

The main difference between arr[:, 0] and arr[:, [0]] is that arr[:, 0] selects the first column of the array, while arr[:, [0]] selects all rows of the array and the first column.

In [ ]:
r = np.array([[1, 55], [100, 25], [32, 150]])
print(r[:, 0])
print(r[:, [0]])

[  1 100  32]
[[  1]
 [100]
 [ 32]]


### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [ ]:
a1 = np.array([[15,16,17],[18,19,20],[21,22,23]] )
a2 = np.array([[20,21,22],[23,24,25],[26,27,28]] )

In [ ]:
a3 = a1*a2

In [ ]:
print(a3)

[[300 336 374]
 [414 456 500]
 [546 594 644]]


### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack([a1,a2]))
print(np.vstack([a1,a2]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [ ]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [ ]:
class Vehicle:
  def __init__(self, name, max_speed, mileage):
    self.name = name
    self.max_speed = max_speed
    self.mileage = mileage

class Bus(Vehicle):
  def __init__(self, name, max_speed, mileage, capacity=50):
    super().__init__(name, max_speed, mileage)
    self.capacity = capacity

  def seating_capacity(self):
    return f"The seating capacity of a {self.name} is {self.capacity} passengers"

bus = Bus("School Bus", 60, 25)

print(bus.seating_capacity())

The seating capacity of a School Bus is 50 passengers


# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [ ]:
# Problem_1 Link:
s = input()
a = s.split('+')
a = sorted(a)
a = '+'.join(a)
print(a)



<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [ ]:
# Problem_2 Link:
s = input()
s = s.lower()
r=''
v =['a', 'e', 'u', 'o', 'i', 'y']
for i in s:
    if(i not in v):
        r = r + '.'+i
print(r)

